//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace izibiz.SERVICES.serviceAuth {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/entity")]
    public partial class REQUEST_ERRORType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long iNTL_TXN_IDField;
        
        private string cLIENT_TXN_IDField;
        
        private int eRROR_CODEField;
        
        private string eRROR_SHORT_DESField;
        
        private string eRROR_LONG_DESField;
        
        private string sTACKTRACEField;
        
        private int eRROR_ELEMENT_INDEXField;
        
        private bool eRROR_ELEMENT_INDEXFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long INTL_TXN_ID {
            get {
                return this.iNTL_TXN_IDField;
            }
            set {
                this.iNTL_TXN_IDField = value;
                this.RaisePropertyChanged("INTL_TXN_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=1)]
        public string CLIENT_TXN_ID {
            get {
                return this.cLIENT_TXN_IDField;
            }
            set {
                this.cLIENT_TXN_IDField = value;
                this.RaisePropertyChanged("CLIENT_TXN_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int ERROR_CODE {
            get {
                return this.eRROR_CODEField;
            }
            set {
                this.eRROR_CODEField = value;
                this.RaisePropertyChanged("ERROR_CODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ERROR_SHORT_DES {
            get {
                return this.eRROR_SHORT_DESField;
            }
            set {
                this.eRROR_SHORT_DESField = value;
                this.RaisePropertyChanged("ERROR_SHORT_DES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ERROR_LONG_DES {
            get {
                return this.eRROR_LONG_DESField;
            }
            set {
                this.eRROR_LONG_DESField = value;
                this.RaisePropertyChanged("ERROR_LONG_DES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string STACKTRACE {
            get {
                return this.sTACKTRACEField;
            }
            set {
                this.sTACKTRACEField = value;
                this.RaisePropertyChanged("STACKTRACE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int ERROR_ELEMENT_INDEX {
            get {
                return this.eRROR_ELEMENT_INDEXField;
            }
            set {
                this.eRROR_ELEMENT_INDEXField = value;
                this.RaisePropertyChanged("ERROR_ELEMENT_INDEX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ERROR_ELEMENT_INDEXSpecified {
            get {
                return this.eRROR_ELEMENT_INDEXFieldSpecified;
            }
            set {
                this.eRROR_ELEMENT_INDEXFieldSpecified = value;
                this.RaisePropertyChanged("ERROR_ELEMENT_INDEXSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/common")]
    public partial class ATTRIBUTESTYPE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nAMEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string NAME {
            get {
                return this.nAMEField;
            }
            set {
                this.nAMEField = value;
                this.RaisePropertyChanged("NAME");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/entity")]
    public partial class REQUEST_INFOType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private REQUEST_HEADERType rEQUEST_HEADERField;
        
        private REQUEST_RETURNType rEQUEST_RETURNField;
        
        private REQUEST_ERRORType rEQUEST_ERRORField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public REQUEST_HEADERType REQUEST_HEADER {
            get {
                return this.rEQUEST_HEADERField;
            }
            set {
                this.rEQUEST_HEADERField = value;
                this.RaisePropertyChanged("REQUEST_HEADER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public REQUEST_RETURNType REQUEST_RETURN {
            get {
                return this.rEQUEST_RETURNField;
            }
            set {
                this.rEQUEST_RETURNField = value;
                this.RaisePropertyChanged("REQUEST_RETURN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public REQUEST_ERRORType REQUEST_ERROR {
            get {
                return this.rEQUEST_ERRORField;
            }
            set {
                this.rEQUEST_ERRORField = value;
                this.RaisePropertyChanged("REQUEST_ERROR");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/entity")]
    public partial class REQUEST_HEADERType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sESSION_IDField;
        
        private string cLIENT_TXN_IDField;
        
        private long iNTL_TXN_IDField;
        
        private bool iNTL_TXN_IDFieldSpecified;
        
        private long iNTL_PARENT_TXN_IDField;
        
        private bool iNTL_PARENT_TXN_IDFieldSpecified;
        
        private System.DateTime aCTION_DATEField;
        
        private bool aCTION_DATEFieldSpecified;
        
        private CHANGE_INFOType cHANGE_INFOField;
        
        private string rEASONField;
        
        private string aPPLICATION_NAMEField;
        
        private string hOSTNAMEField;
        
        private string cHANNEL_NAMEField;
        
        private string sIMULATION_FLAGField;
        
        private string cOMPRESSEDField;
        
        private ATTRIBUTESTYPE[] aTTRIBUTESField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=0)]
        public string SESSION_ID {
            get {
                return this.sESSION_IDField;
            }
            set {
                this.sESSION_IDField = value;
                this.RaisePropertyChanged("SESSION_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=1)]
        public string CLIENT_TXN_ID {
            get {
                return this.cLIENT_TXN_IDField;
            }
            set {
                this.cLIENT_TXN_IDField = value;
                this.RaisePropertyChanged("CLIENT_TXN_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long INTL_TXN_ID {
            get {
                return this.iNTL_TXN_IDField;
            }
            set {
                this.iNTL_TXN_IDField = value;
                this.RaisePropertyChanged("INTL_TXN_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool INTL_TXN_IDSpecified {
            get {
                return this.iNTL_TXN_IDFieldSpecified;
            }
            set {
                this.iNTL_TXN_IDFieldSpecified = value;
                this.RaisePropertyChanged("INTL_TXN_IDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long INTL_PARENT_TXN_ID {
            get {
                return this.iNTL_PARENT_TXN_IDField;
            }
            set {
                this.iNTL_PARENT_TXN_IDField = value;
                this.RaisePropertyChanged("INTL_PARENT_TXN_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool INTL_PARENT_TXN_IDSpecified {
            get {
                return this.iNTL_PARENT_TXN_IDFieldSpecified;
            }
            set {
                this.iNTL_PARENT_TXN_IDFieldSpecified = value;
                this.RaisePropertyChanged("INTL_PARENT_TXN_IDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime ACTION_DATE {
            get {
                return this.aCTION_DATEField;
            }
            set {
                this.aCTION_DATEField = value;
                this.RaisePropertyChanged("ACTION_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ACTION_DATESpecified {
            get {
                return this.aCTION_DATEFieldSpecified;
            }
            set {
                this.aCTION_DATEFieldSpecified = value;
                this.RaisePropertyChanged("ACTION_DATESpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public CHANGE_INFOType CHANGE_INFO {
            get {
                return this.cHANGE_INFOField;
            }
            set {
                this.cHANGE_INFOField = value;
                this.RaisePropertyChanged("CHANGE_INFO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=6)]
        public string REASON {
            get {
                return this.rEASONField;
            }
            set {
                this.rEASONField = value;
                this.RaisePropertyChanged("REASON");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=7)]
        public string APPLICATION_NAME {
            get {
                return this.aPPLICATION_NAMEField;
            }
            set {
                this.aPPLICATION_NAMEField = value;
                this.RaisePropertyChanged("APPLICATION_NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=8)]
        public string HOSTNAME {
            get {
                return this.hOSTNAMEField;
            }
            set {
                this.hOSTNAMEField = value;
                this.RaisePropertyChanged("HOSTNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=9)]
        public string CHANNEL_NAME {
            get {
                return this.cHANNEL_NAMEField;
            }
            set {
                this.cHANNEL_NAMEField = value;
                this.RaisePropertyChanged("CHANNEL_NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=10)]
        public string SIMULATION_FLAG {
            get {
                return this.sIMULATION_FLAGField;
            }
            set {
                this.sIMULATION_FLAGField = value;
                this.RaisePropertyChanged("SIMULATION_FLAG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=11)]
        public string COMPRESSED {
            get {
                return this.cOMPRESSEDField;
            }
            set {
                this.cOMPRESSEDField = value;
                this.RaisePropertyChanged("COMPRESSED");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ATTRIBUTES", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public ATTRIBUTESTYPE[] ATTRIBUTES {
            get {
                return this.aTTRIBUTESField;
            }
            set {
                this.aTTRIBUTESField = value;
                this.RaisePropertyChanged("ATTRIBUTES");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/common")]
    public partial class CHANGE_INFOType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime cDATEField;
        
        private long cPOSITION_IDField;
        
        private long cUSER_IDField;
        
        private System.DateTime uDATEField;
        
        private bool uDATEFieldSpecified;
        
        private long uPOSITION_IDField;
        
        private bool uPOSITION_IDFieldSpecified;
        
        private long uUSER_IDField;
        
        private bool uUSER_IDFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=0)]
        public System.DateTime CDATE {
            get {
                return this.cDATEField;
            }
            set {
                this.cDATEField = value;
                this.RaisePropertyChanged("CDATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long CPOSITION_ID {
            get {
                return this.cPOSITION_IDField;
            }
            set {
                this.cPOSITION_IDField = value;
                this.RaisePropertyChanged("CPOSITION_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long CUSER_ID {
            get {
                return this.cUSER_IDField;
            }
            set {
                this.cUSER_IDField = value;
                this.RaisePropertyChanged("CUSER_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=3)]
        public System.DateTime UDATE {
            get {
                return this.uDATEField;
            }
            set {
                this.uDATEField = value;
                this.RaisePropertyChanged("UDATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UDATESpecified {
            get {
                return this.uDATEFieldSpecified;
            }
            set {
                this.uDATEFieldSpecified = value;
                this.RaisePropertyChanged("UDATESpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public long UPOSITION_ID {
            get {
                return this.uPOSITION_IDField;
            }
            set {
                this.uPOSITION_IDField = value;
                this.RaisePropertyChanged("UPOSITION_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UPOSITION_IDSpecified {
            get {
                return this.uPOSITION_IDFieldSpecified;
            }
            set {
                this.uPOSITION_IDFieldSpecified = value;
                this.RaisePropertyChanged("UPOSITION_IDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public long UUSER_ID {
            get {
                return this.uUSER_IDField;
            }
            set {
                this.uUSER_IDField = value;
                this.RaisePropertyChanged("UUSER_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UUSER_IDSpecified {
            get {
                return this.uUSER_IDFieldSpecified;
            }
            set {
                this.uUSER_IDFieldSpecified = value;
                this.RaisePropertyChanged("UUSER_IDSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/entity")]
    public partial class REQUEST_RETURNType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long iNTL_TXN_IDField;
        
        private string cLIENT_TXN_IDField;
        
        private int rETURN_CODEField;
        
        private string[] wARNINGSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long INTL_TXN_ID {
            get {
                return this.iNTL_TXN_IDField;
            }
            set {
                this.iNTL_TXN_IDField = value;
                this.RaisePropertyChanged("INTL_TXN_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=1)]
        public string CLIENT_TXN_ID {
            get {
                return this.cLIENT_TXN_IDField;
            }
            set {
                this.cLIENT_TXN_IDField = value;
                this.RaisePropertyChanged("CLIENT_TXN_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int RETURN_CODE {
            get {
                return this.rETURN_CODEField;
            }
            set {
                this.rETURN_CODEField = value;
                this.RaisePropertyChanged("RETURN_CODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("WARNINGS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string[] WARNINGS {
            get {
                return this.wARNINGSField;
            }
            set {
                this.wARNINGSField = value;
                this.RaisePropertyChanged("WARNINGS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/common")]
    public partial class PARTINFO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vKNField;
        
        private string iDENTIFIERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string VKN {
            get {
                return this.vKNField;
            }
            set {
                this.vKNField = value;
                this.RaisePropertyChanged("VKN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string IDENTIFIER {
            get {
                return this.iDENTIFIERField;
            }
            set {
                this.iDENTIFIERField = value;
                this.RaisePropertyChanged("IDENTIFIER");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/common")]
    public partial class LOV_VALUEType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long lOV_IDField;
        
        private string lOV_CODEField;
        
        public LOV_VALUEType() {
            this.lOV_CODEField = "\'N\'";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long LOV_ID {
            get {
                return this.lOV_IDField;
            }
            set {
                this.lOV_IDField = value;
                this.RaisePropertyChanged("LOV_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=1)]
        [System.ComponentModel.DefaultValueAttribute("\'N\'")]
        public string LOV_CODE {
            get {
                return this.lOV_CODEField;
            }
            set {
                this.lOV_CODEField = value;
                this.RaisePropertyChanged("LOV_CODE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class GIBUSER : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iDENTIFIERField;
        
        private string aLIASField;
        
        private string tITLEField;
        
        private string tYPEField;
        
        private string rEGISTER_TIMEField;
        
        private string uNITField;
        
        private string aLIAS_CREATION_TIMEField;
        
        private string aCCOUNT_TYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string IDENTIFIER {
            get {
                return this.iDENTIFIERField;
            }
            set {
                this.iDENTIFIERField = value;
                this.RaisePropertyChanged("IDENTIFIER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ALIAS {
            get {
                return this.aLIASField;
            }
            set {
                this.aLIASField = value;
                this.RaisePropertyChanged("ALIAS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TITLE {
            get {
                return this.tITLEField;
            }
            set {
                this.tITLEField = value;
                this.RaisePropertyChanged("TITLE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
                this.RaisePropertyChanged("TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string REGISTER_TIME {
            get {
                return this.rEGISTER_TIMEField;
            }
            set {
                this.rEGISTER_TIMEField = value;
                this.RaisePropertyChanged("REGISTER_TIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=5)]
        public string UNIT {
            get {
                return this.uNITField;
            }
            set {
                this.uNITField = value;
                this.RaisePropertyChanged("UNIT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ALIAS_CREATION_TIME {
            get {
                return this.aLIAS_CREATION_TIMEField;
            }
            set {
                this.aLIAS_CREATION_TIMEField = value;
                this.RaisePropertyChanged("ALIAS_CREATION_TIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string ACCOUNT_TYPE {
            get {
                return this.aCCOUNT_TYPEField;
            }
            set {
                this.aCCOUNT_TYPEField = value;
                this.RaisePropertyChanged("ACCOUNT_TYPE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class CheckUserResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private REQUEST_ERRORType eRROR_TYPEField;
        
        private GIBUSER[] uSERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public REQUEST_ERRORType ERROR_TYPE {
            get {
                return this.eRROR_TYPEField;
            }
            set {
                this.eRROR_TYPEField = value;
                this.RaisePropertyChanged("ERROR_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("USER", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public GIBUSER[] USER {
            get {
                return this.uSERField;
            }
            set {
                this.uSERField = value;
                this.RaisePropertyChanged("USER");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class GetUserAuthorizationResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AUTHORIZED aUTHORIZEDField;
        
        private bool aUTHORIZEDFieldSpecified;
        
        private REQUEST_ERRORType eRROR_TYPEField;
        
        private PRODUCT[] pRODUCT_LISTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public AUTHORIZED AUTHORIZED {
            get {
                return this.aUTHORIZEDField;
            }
            set {
                this.aUTHORIZEDField = value;
                this.RaisePropertyChanged("AUTHORIZED");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AUTHORIZEDSpecified {
            get {
                return this.aUTHORIZEDFieldSpecified;
            }
            set {
                this.aUTHORIZEDFieldSpecified = value;
                this.RaisePropertyChanged("AUTHORIZEDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public REQUEST_ERRORType ERROR_TYPE {
            get {
                return this.eRROR_TYPEField;
            }
            set {
                this.eRROR_TYPEField = value;
                this.RaisePropertyChanged("ERROR_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public PRODUCT[] PRODUCT_LIST {
            get {
                return this.pRODUCT_LISTField;
            }
            set {
                this.pRODUCT_LISTField = value;
                this.RaisePropertyChanged("PRODUCT_LIST");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public enum AUTHORIZED {
        
        /// <remarks/>
        Y,
        
        /// <remarks/>
        N,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public enum PRODUCT {
        
        /// <remarks/>
        EINVOICE,
        
        /// <remarks/>
        EARCHIVE,
        
        /// <remarks/>
        EDESPATCH,
        
        /// <remarks/>
        CREDITNOTE,
        
        /// <remarks/>
        RECONCILIATION,
        
        /// <remarks/>
        CONNECTOR,
        
        /// <remarks/>
        ELEDGER,
        
        /// <remarks/>
        ELEDGERARCHIVE,
        
        /// <remarks/>
        EINVOICEARCHIVE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("EINVOICEARCHIVE")]
        EINVOICEARCHIVE1,
        
        /// <remarks/>
        ESMM,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2005/05/xmlmime")]
    public partial class base64Binary : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contentTypeField;
        
        private byte[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string contentType {
            get {
                return this.contentTypeField;
            }
            set {
                this.contentTypeField = value;
                this.RaisePropertyChanged("contentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
        public byte[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class GetGibUserListResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CONTENT", typeof(base64Binary), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ERROR_TYPE", typeof(REQUEST_ERRORType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class LogoutResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private REQUEST_RETURNType rEQUEST_RETURNField;
        
        private REQUEST_ERRORType eRROR_TYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public REQUEST_RETURNType REQUEST_RETURN {
            get {
                return this.rEQUEST_RETURNField;
            }
            set {
                this.rEQUEST_RETURNField = value;
                this.RaisePropertyChanged("REQUEST_RETURN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public REQUEST_ERRORType ERROR_TYPE {
            get {
                return this.eRROR_TYPEField;
            }
            set {
                this.eRROR_TYPEField = value;
                this.RaisePropertyChanged("ERROR_TYPE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class LoginResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sESSION_IDField;
        
        private REQUEST_ERRORType eRROR_TYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=0)]
        public string SESSION_ID {
            get {
                return this.sESSION_IDField;
            }
            set {
                this.sESSION_IDField = value;
                this.RaisePropertyChanged("SESSION_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public REQUEST_ERRORType ERROR_TYPE {
            get {
                return this.eRROR_TYPEField;
            }
            set {
                this.eRROR_TYPEField = value;
                this.RaisePropertyChanged("ERROR_TYPE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CheckUserRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetUserAuthorizationRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetGibUserListRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LogoutRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LoginRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/entity")]
    public partial class REQUEST : object, System.ComponentModel.INotifyPropertyChanged {
        
        private REQUEST_HEADERType rEQUEST_HEADERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public REQUEST_HEADERType REQUEST_HEADER {
            get {
                return this.rEQUEST_HEADERField;
            }
            set {
                this.rEQUEST_HEADERField = value;
                this.RaisePropertyChanged("REQUEST_HEADER");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class CheckUserRequest : REQUEST {
        
        private GIBUSER uSERField;
        
        private string dOCUMENT_TYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public GIBUSER USER {
            get {
                return this.uSERField;
            }
            set {
                this.uSERField = value;
                this.RaisePropertyChanged("USER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=1)]
        public string DOCUMENT_TYPE {
            get {
                return this.dOCUMENT_TYPEField;
            }
            set {
                this.dOCUMENT_TYPEField = value;
                this.RaisePropertyChanged("DOCUMENT_TYPE");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class GetUserAuthorizationRequest : REQUEST {
        
        private PRODUCT pRODUCTField;
        
        private PRODUCT_DETAIL_FLAG pRODUCT_DETAIL_FLAGField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public PRODUCT PRODUCT {
            get {
                return this.pRODUCTField;
            }
            set {
                this.pRODUCTField = value;
                this.RaisePropertyChanged("PRODUCT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public PRODUCT_DETAIL_FLAG PRODUCT_DETAIL_FLAG {
            get {
                return this.pRODUCT_DETAIL_FLAGField;
            }
            set {
                this.pRODUCT_DETAIL_FLAGField = value;
                this.RaisePropertyChanged("PRODUCT_DETAIL_FLAG");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public enum PRODUCT_DETAIL_FLAG {
        
        /// <remarks/>
        Y,
        
        /// <remarks/>
        N,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class GetGibUserListRequest : REQUEST {
        
        private GetGibUserListRequestTYPE tYPEField;
        
        private string dOCUMENT_TYPEField;
        
        private System.DateTime rEGISTER_TIME_STARTField;
        
        private bool rEGISTER_TIME_STARTFieldSpecified;
        
        public GetGibUserListRequest() {
            this.tYPEField = GetGibUserListRequestTYPE.XML;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.ComponentModel.DefaultValueAttribute(GetGibUserListRequestTYPE.XML)]
        public GetGibUserListRequestTYPE TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
                this.RaisePropertyChanged("TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=1)]
        public string DOCUMENT_TYPE {
            get {
                return this.dOCUMENT_TYPEField;
            }
            set {
                this.dOCUMENT_TYPEField = value;
                this.RaisePropertyChanged("DOCUMENT_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime REGISTER_TIME_START {
            get {
                return this.rEGISTER_TIME_STARTField;
            }
            set {
                this.rEGISTER_TIME_STARTField = value;
                this.RaisePropertyChanged("REGISTER_TIME_START");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool REGISTER_TIME_STARTSpecified {
            get {
                return this.rEGISTER_TIME_STARTFieldSpecified;
            }
            set {
                this.rEGISTER_TIME_STARTFieldSpecified = value;
                this.RaisePropertyChanged("REGISTER_TIME_STARTSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.i2i.com/ei/wsdl")]
    public enum GetGibUserListRequestTYPE {
        
        /// <remarks/>
        CSV,
        
        /// <remarks/>
        XML,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class LogoutRequest : REQUEST {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class LoginRequest : REQUEST {
        
        private string uSER_NAMEField;
        
        private string pASSWORDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string USER_NAME {
            get {
                return this.uSER_NAMEField;
            }
            set {
                this.uSER_NAMEField = value;
                this.RaisePropertyChanged("USER_NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string PASSWORD {
            get {
                return this.pASSWORDField;
            }
            set {
                this.pASSWORDField = value;
                this.RaisePropertyChanged("PASSWORD");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.i2i.com/ei/wsdl", ConfigurationName="serviceAuth.AuthenticationServicePort")]
    public interface AuthenticationServicePort {
        
        // CODEGEN: Generating message contract since the operation Login is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(izibiz.SERVICES.serviceAuth.REQUEST_ERRORType), Action="", Name="RequestFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(REQUEST_INFOType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PARTINFO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LOV_VALUEType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckUserResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetUserAuthorizationResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetGibUserListResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LogoutResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(REQUEST))]
        izibiz.SERVICES.serviceAuth.LoginResponse1 Login(izibiz.SERVICES.serviceAuth.LoginRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<izibiz.SERVICES.serviceAuth.LoginResponse1> LoginAsync(izibiz.SERVICES.serviceAuth.LoginRequest1 request);
        
        // CODEGEN: Generating message contract since the operation Logout is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(izibiz.SERVICES.serviceAuth.REQUEST_ERRORType), Action="", Name="RequestFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(REQUEST_INFOType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PARTINFO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LOV_VALUEType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckUserResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetUserAuthorizationResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetGibUserListResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LogoutResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(REQUEST))]
        izibiz.SERVICES.serviceAuth.LogoutResponse1 Logout(izibiz.SERVICES.serviceAuth.LogoutRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<izibiz.SERVICES.serviceAuth.LogoutResponse1> LogoutAsync(izibiz.SERVICES.serviceAuth.LogoutRequest1 request);
        
        // CODEGEN: Generating message contract since the operation GetGibUserList is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(izibiz.SERVICES.serviceAuth.REQUEST_ERRORType), Action="", Name="RequestFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(REQUEST_INFOType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PARTINFO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LOV_VALUEType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckUserResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetUserAuthorizationResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetGibUserListResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LogoutResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(REQUEST))]
        izibiz.SERVICES.serviceAuth.GetGibUserListResponse1 GetGibUserList(izibiz.SERVICES.serviceAuth.GetGibUserListRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<izibiz.SERVICES.serviceAuth.GetGibUserListResponse1> GetGibUserListAsync(izibiz.SERVICES.serviceAuth.GetGibUserListRequest1 request);
        
        // CODEGEN: Generating message contract since the operation CheckUser is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(izibiz.SERVICES.serviceAuth.REQUEST_ERRORType), Action="", Name="RequestFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(REQUEST_INFOType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PARTINFO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LOV_VALUEType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckUserResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetUserAuthorizationResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetGibUserListResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LogoutResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(REQUEST))]
        izibiz.SERVICES.serviceAuth.CheckUserResponse1 CheckUser(izibiz.SERVICES.serviceAuth.CheckUserRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<izibiz.SERVICES.serviceAuth.CheckUserResponse1> CheckUserAsync(izibiz.SERVICES.serviceAuth.CheckUserRequest1 request);
        
        // CODEGEN: Generating message contract since the operation GetUserAuthorization is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(izibiz.SERVICES.serviceAuth.REQUEST_ERRORType), Action="", Name="RequestFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(REQUEST_INFOType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PARTINFO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LOV_VALUEType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckUserResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetUserAuthorizationResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetGibUserListResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LogoutResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(REQUEST))]
        izibiz.SERVICES.serviceAuth.GetUserAuthorizationResponse1 GetUserAuthorization(izibiz.SERVICES.serviceAuth.GetUserAuthorizationRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<izibiz.SERVICES.serviceAuth.GetUserAuthorizationResponse1> GetUserAuthorizationAsync(izibiz.SERVICES.serviceAuth.GetUserAuthorizationRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.i2i.com/ei/wsdl", Order=0)]
        public izibiz.SERVICES.serviceAuth.LoginRequest LoginRequest;
        
        public LoginRequest1() {
        }
        
        public LoginRequest1(izibiz.SERVICES.serviceAuth.LoginRequest LoginRequest) {
            this.LoginRequest = LoginRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.i2i.com/ei/wsdl", Order=0)]
        public izibiz.SERVICES.serviceAuth.LoginResponse LoginResponse;
        
        public LoginResponse1() {
        }
        
        public LoginResponse1(izibiz.SERVICES.serviceAuth.LoginResponse LoginResponse) {
            this.LoginResponse = LoginResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.i2i.com/ei/wsdl", Order=0)]
        public izibiz.SERVICES.serviceAuth.LogoutRequest LogoutRequest;
        
        public LogoutRequest1() {
        }
        
        public LogoutRequest1(izibiz.SERVICES.serviceAuth.LogoutRequest LogoutRequest) {
            this.LogoutRequest = LogoutRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.i2i.com/ei/wsdl", Order=0)]
        public izibiz.SERVICES.serviceAuth.LogoutResponse LogoutResponse;
        
        public LogoutResponse1() {
        }
        
        public LogoutResponse1(izibiz.SERVICES.serviceAuth.LogoutResponse LogoutResponse) {
            this.LogoutResponse = LogoutResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGibUserListRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.i2i.com/ei/wsdl", Order=0)]
        public izibiz.SERVICES.serviceAuth.GetGibUserListRequest GetGibUserListRequest;
        
        public GetGibUserListRequest1() {
        }
        
        public GetGibUserListRequest1(izibiz.SERVICES.serviceAuth.GetGibUserListRequest GetGibUserListRequest) {
            this.GetGibUserListRequest = GetGibUserListRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGibUserListResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.i2i.com/ei/wsdl", Order=0)]
        public izibiz.SERVICES.serviceAuth.GetGibUserListResponse GetGibUserListResponse;
        
        public GetGibUserListResponse1() {
        }
        
        public GetGibUserListResponse1(izibiz.SERVICES.serviceAuth.GetGibUserListResponse GetGibUserListResponse) {
            this.GetGibUserListResponse = GetGibUserListResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckUserRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.i2i.com/ei/wsdl", Order=0)]
        public izibiz.SERVICES.serviceAuth.CheckUserRequest CheckUserRequest;
        
        public CheckUserRequest1() {
        }
        
        public CheckUserRequest1(izibiz.SERVICES.serviceAuth.CheckUserRequest CheckUserRequest) {
            this.CheckUserRequest = CheckUserRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckUserResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.i2i.com/ei/wsdl", Order=0)]
        public izibiz.SERVICES.serviceAuth.CheckUserResponse CheckUserResponse;
        
        public CheckUserResponse1() {
        }
        
        public CheckUserResponse1(izibiz.SERVICES.serviceAuth.CheckUserResponse CheckUserResponse) {
            this.CheckUserResponse = CheckUserResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserAuthorizationRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.i2i.com/ei/wsdl", Order=0)]
        public izibiz.SERVICES.serviceAuth.GetUserAuthorizationRequest GetUserAuthorizationRequest;
        
        public GetUserAuthorizationRequest1() {
        }
        
        public GetUserAuthorizationRequest1(izibiz.SERVICES.serviceAuth.GetUserAuthorizationRequest GetUserAuthorizationRequest) {
            this.GetUserAuthorizationRequest = GetUserAuthorizationRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserAuthorizationResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.i2i.com/ei/wsdl", Order=0)]
        public izibiz.SERVICES.serviceAuth.GetUserAuthorizationResponse GetUserAuthorizationResponse;
        
        public GetUserAuthorizationResponse1() {
        }
        
        public GetUserAuthorizationResponse1(izibiz.SERVICES.serviceAuth.GetUserAuthorizationResponse GetUserAuthorizationResponse) {
            this.GetUserAuthorizationResponse = GetUserAuthorizationResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AuthenticationServicePortChannel : izibiz.SERVICES.serviceAuth.AuthenticationServicePort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthenticationServicePortClient : System.ServiceModel.ClientBase<izibiz.SERVICES.serviceAuth.AuthenticationServicePort>, izibiz.SERVICES.serviceAuth.AuthenticationServicePort {
        
        public AuthenticationServicePortClient() {
        }
        
        public AuthenticationServicePortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthenticationServicePortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticationServicePortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticationServicePortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        izibiz.SERVICES.serviceAuth.LoginResponse1 izibiz.SERVICES.serviceAuth.AuthenticationServicePort.Login(izibiz.SERVICES.serviceAuth.LoginRequest1 request) {
            return base.Channel.Login(request);
        }
        
        public izibiz.SERVICES.serviceAuth.LoginResponse Login(izibiz.SERVICES.serviceAuth.LoginRequest LoginRequest) {
            izibiz.SERVICES.serviceAuth.LoginRequest1 inValue = new izibiz.SERVICES.serviceAuth.LoginRequest1();
            inValue.LoginRequest = LoginRequest;
            izibiz.SERVICES.serviceAuth.LoginResponse1 retVal = ((izibiz.SERVICES.serviceAuth.AuthenticationServicePort)(this)).Login(inValue);
            return retVal.LoginResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<izibiz.SERVICES.serviceAuth.LoginResponse1> izibiz.SERVICES.serviceAuth.AuthenticationServicePort.LoginAsync(izibiz.SERVICES.serviceAuth.LoginRequest1 request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<izibiz.SERVICES.serviceAuth.LoginResponse1> LoginAsync(izibiz.SERVICES.serviceAuth.LoginRequest LoginRequest) {
            izibiz.SERVICES.serviceAuth.LoginRequest1 inValue = new izibiz.SERVICES.serviceAuth.LoginRequest1();
            inValue.LoginRequest = LoginRequest;
            return ((izibiz.SERVICES.serviceAuth.AuthenticationServicePort)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        izibiz.SERVICES.serviceAuth.LogoutResponse1 izibiz.SERVICES.serviceAuth.AuthenticationServicePort.Logout(izibiz.SERVICES.serviceAuth.LogoutRequest1 request) {
            return base.Channel.Logout(request);
        }
        
        public izibiz.SERVICES.serviceAuth.LogoutResponse Logout(izibiz.SERVICES.serviceAuth.LogoutRequest LogoutRequest) {
            izibiz.SERVICES.serviceAuth.LogoutRequest1 inValue = new izibiz.SERVICES.serviceAuth.LogoutRequest1();
            inValue.LogoutRequest = LogoutRequest;
            izibiz.SERVICES.serviceAuth.LogoutResponse1 retVal = ((izibiz.SERVICES.serviceAuth.AuthenticationServicePort)(this)).Logout(inValue);
            return retVal.LogoutResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<izibiz.SERVICES.serviceAuth.LogoutResponse1> izibiz.SERVICES.serviceAuth.AuthenticationServicePort.LogoutAsync(izibiz.SERVICES.serviceAuth.LogoutRequest1 request) {
            return base.Channel.LogoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<izibiz.SERVICES.serviceAuth.LogoutResponse1> LogoutAsync(izibiz.SERVICES.serviceAuth.LogoutRequest LogoutRequest) {
            izibiz.SERVICES.serviceAuth.LogoutRequest1 inValue = new izibiz.SERVICES.serviceAuth.LogoutRequest1();
            inValue.LogoutRequest = LogoutRequest;
            return ((izibiz.SERVICES.serviceAuth.AuthenticationServicePort)(this)).LogoutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        izibiz.SERVICES.serviceAuth.GetGibUserListResponse1 izibiz.SERVICES.serviceAuth.AuthenticationServicePort.GetGibUserList(izibiz.SERVICES.serviceAuth.GetGibUserListRequest1 request) {
            return base.Channel.GetGibUserList(request);
        }
        
        public izibiz.SERVICES.serviceAuth.GetGibUserListResponse GetGibUserList(izibiz.SERVICES.serviceAuth.GetGibUserListRequest GetGibUserListRequest) {
            izibiz.SERVICES.serviceAuth.GetGibUserListRequest1 inValue = new izibiz.SERVICES.serviceAuth.GetGibUserListRequest1();
            inValue.GetGibUserListRequest = GetGibUserListRequest;
            izibiz.SERVICES.serviceAuth.GetGibUserListResponse1 retVal = ((izibiz.SERVICES.serviceAuth.AuthenticationServicePort)(this)).GetGibUserList(inValue);
            return retVal.GetGibUserListResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<izibiz.SERVICES.serviceAuth.GetGibUserListResponse1> izibiz.SERVICES.serviceAuth.AuthenticationServicePort.GetGibUserListAsync(izibiz.SERVICES.serviceAuth.GetGibUserListRequest1 request) {
            return base.Channel.GetGibUserListAsync(request);
        }
        
        public System.Threading.Tasks.Task<izibiz.SERVICES.serviceAuth.GetGibUserListResponse1> GetGibUserListAsync(izibiz.SERVICES.serviceAuth.GetGibUserListRequest GetGibUserListRequest) {
            izibiz.SERVICES.serviceAuth.GetGibUserListRequest1 inValue = new izibiz.SERVICES.serviceAuth.GetGibUserListRequest1();
            inValue.GetGibUserListRequest = GetGibUserListRequest;
            return ((izibiz.SERVICES.serviceAuth.AuthenticationServicePort)(this)).GetGibUserListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        izibiz.SERVICES.serviceAuth.CheckUserResponse1 izibiz.SERVICES.serviceAuth.AuthenticationServicePort.CheckUser(izibiz.SERVICES.serviceAuth.CheckUserRequest1 request) {
            return base.Channel.CheckUser(request);
        }
        
        public izibiz.SERVICES.serviceAuth.CheckUserResponse CheckUser(izibiz.SERVICES.serviceAuth.CheckUserRequest CheckUserRequest) {
            izibiz.SERVICES.serviceAuth.CheckUserRequest1 inValue = new izibiz.SERVICES.serviceAuth.CheckUserRequest1();
            inValue.CheckUserRequest = CheckUserRequest;
            izibiz.SERVICES.serviceAuth.CheckUserResponse1 retVal = ((izibiz.SERVICES.serviceAuth.AuthenticationServicePort)(this)).CheckUser(inValue);
            return retVal.CheckUserResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<izibiz.SERVICES.serviceAuth.CheckUserResponse1> izibiz.SERVICES.serviceAuth.AuthenticationServicePort.CheckUserAsync(izibiz.SERVICES.serviceAuth.CheckUserRequest1 request) {
            return base.Channel.CheckUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<izibiz.SERVICES.serviceAuth.CheckUserResponse1> CheckUserAsync(izibiz.SERVICES.serviceAuth.CheckUserRequest CheckUserRequest) {
            izibiz.SERVICES.serviceAuth.CheckUserRequest1 inValue = new izibiz.SERVICES.serviceAuth.CheckUserRequest1();
            inValue.CheckUserRequest = CheckUserRequest;
            return ((izibiz.SERVICES.serviceAuth.AuthenticationServicePort)(this)).CheckUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        izibiz.SERVICES.serviceAuth.GetUserAuthorizationResponse1 izibiz.SERVICES.serviceAuth.AuthenticationServicePort.GetUserAuthorization(izibiz.SERVICES.serviceAuth.GetUserAuthorizationRequest1 request) {
            return base.Channel.GetUserAuthorization(request);
        }
        
        public izibiz.SERVICES.serviceAuth.GetUserAuthorizationResponse GetUserAuthorization(izibiz.SERVICES.serviceAuth.GetUserAuthorizationRequest GetUserAuthorizationRequest) {
            izibiz.SERVICES.serviceAuth.GetUserAuthorizationRequest1 inValue = new izibiz.SERVICES.serviceAuth.GetUserAuthorizationRequest1();
            inValue.GetUserAuthorizationRequest = GetUserAuthorizationRequest;
            izibiz.SERVICES.serviceAuth.GetUserAuthorizationResponse1 retVal = ((izibiz.SERVICES.serviceAuth.AuthenticationServicePort)(this)).GetUserAuthorization(inValue);
            return retVal.GetUserAuthorizationResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<izibiz.SERVICES.serviceAuth.GetUserAuthorizationResponse1> izibiz.SERVICES.serviceAuth.AuthenticationServicePort.GetUserAuthorizationAsync(izibiz.SERVICES.serviceAuth.GetUserAuthorizationRequest1 request) {
            return base.Channel.GetUserAuthorizationAsync(request);
        }
        
        public System.Threading.Tasks.Task<izibiz.SERVICES.serviceAuth.GetUserAuthorizationResponse1> GetUserAuthorizationAsync(izibiz.SERVICES.serviceAuth.GetUserAuthorizationRequest GetUserAuthorizationRequest) {
            izibiz.SERVICES.serviceAuth.GetUserAuthorizationRequest1 inValue = new izibiz.SERVICES.serviceAuth.GetUserAuthorizationRequest1();
            inValue.GetUserAuthorizationRequest = GetUserAuthorizationRequest;
            return ((izibiz.SERVICES.serviceAuth.AuthenticationServicePort)(this)).GetUserAuthorizationAsync(inValue);
        }
    }
}
