//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace izibiz.UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("izibiz.UI.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil Seçimi.
        /// </summary>
        internal static string ch_language {
            get {
                return ResourceManager.GetString("ch_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E- Arşiv.
        /// </summary>
        internal static string e_arsiv {
            get {
                return ResourceManager.GetString("e-arsiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E- Fatura.
        /// </summary>
        internal static string e_fatura {
            get {
                return ResourceManager.GetString("e-fatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-İrsailye.
        /// </summary>
        internal static string e_irsaliye {
            get {
                return ResourceManager.GetString("e-irsaliye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İzibiz Masaüstü | E-Fatura İşlemleri.
        /// </summary>
        internal static string form_fatura {
            get {
                return ResourceManager.GetString("form_fatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İzibiz Masaüstü | Anasayfa.
        /// </summary>
        internal static string form_home_title {
            get {
                return ResourceManager.GetString("form_home_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İzibiz Masaüstü | Giriş.
        /// </summary>
        internal static string form_login_title {
            get {
                return ResourceManager.GetString("form_login_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yap.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı veya şifre boş bırakılamaz.
        /// </summary>
        internal static string loginBadRequest {
            get {
                return ResourceManager.GetString("loginBadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giris yapılamadı.. Kullanıcı adı ve kontrol ediniz...
        /// </summary>
        internal static string loginWarring {
            get {
                return ResourceManager.GetString("loginWarring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreyi Göster.
        /// </summary>
        internal static string showPassword {
            get {
                return ResourceManager.GetString("showPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı.
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
    }
}
