//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace izibiz.UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("izibiz.UI.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kabul Et.
        /// </summary>
        internal static string accept {
            get {
                return ResourceManager.GetString("accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taslak Faturalar.
        /// </summary>
        internal static string arshiveInvoice {
            get {
                return ResourceManager.GetString("arshiveInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil Seçimi.
        /// </summary>
        internal static string ch_language {
            get {
                return ResourceManager.GetString("ch_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelen Faturalar.
        /// </summary>
        internal static string commingInvoice {
            get {
                return ResourceManager.GetString("commingInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E- Arşiv.
        /// </summary>
        internal static string eArsiv {
            get {
                return ResourceManager.GetString("eArsiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E- Fatura.
        /// </summary>
        internal static string eFatura {
            get {
                return ResourceManager.GetString("eFatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-İrsailye.
        /// </summary>
        internal static string eIrsaliye {
            get {
                return ResourceManager.GetString("eIrsaliye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Müstahsil.
        /// </summary>
        internal static string eMustahsil {
            get {
                return ResourceManager.GetString("eMustahsil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mutabakat.
        /// </summary>
        internal static string eReconciliation {
            get {
                return ResourceManager.GetString("eReconciliation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E- Serbest Meslek.
        /// </summary>
        internal static string eSerbestMeslek {
            get {
                return ResourceManager.GetString("eSerbestMeslek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İzibiz Masaüstü | E-Fatura İşlemleri.
        /// </summary>
        internal static string formFatura {
            get {
                return ResourceManager.GetString("formFatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İzibiz Masaüstü | Anasayfa.
        /// </summary>
        internal static string formHomeTitle {
            get {
                return ResourceManager.GetString("formHomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İzibiz Masaüstü | Giriş.
        /// </summary>
        internal static string formLoginTitle {
            get {
                return ResourceManager.GetString("formLoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelen Fatura Listesi.
        /// </summary>
        internal static string listCommingInvoice {
            get {
                return ResourceManager.GetString("listCommingInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yap.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı veya şifre boş bırakılamaz.
        /// </summary>
        internal static string loginBadRequest {
            get {
                return ResourceManager.GetString("loginBadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giris yapılamadı.. Kullanıcı adı ve kontrol ediniz...
        /// </summary>
        internal static string loginWarring {
            get {
                return ResourceManager.GetString("loginWarring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +Yeni Fatura.
        /// </summary>
        internal static string newInvoice {
            get {
                return ResourceManager.GetString("newInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Et.
        /// </summary>
        internal static string reject {
            get {
                return ResourceManager.GetString("reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönderilen Faturalar.
        /// </summary>
        internal static string sentInvoice {
            get {
                return ResourceManager.GetString("sentInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayarlar.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreyi Göster.
        /// </summary>
        internal static string showPassword {
            get {
                return ResourceManager.GetString("showPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı.
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
    }
}
