//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace izibiz.UI.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("izibiz.UI.Languages.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kabul Et.
        /// </summary>
        internal static string accept {
            get {
                return ResourceManager.GetString("accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama Ekle.
        /// </summary>
        internal static string addDescription {
            get {
                return ResourceManager.GetString("addDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tekrar Gönder.
        /// </summary>
        internal static string againSent {
            get {
                return ResourceManager.GetString("againSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil Seçimi.
        /// </summary>
        internal static string chooseLanguage {
            get {
                return ResourceManager.GetString("chooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taslak Faturalar.
        /// </summary>
        internal static string draftInvoice {
            get {
                return ResourceManager.GetString("draftInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E- Arşiv.
        /// </summary>
        internal static string eArchive {
            get {
                return ResourceManager.GetString("eArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-İrsailye.
        /// </summary>
        internal static string eDispatch {
            get {
                return ResourceManager.GetString("eDispatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E- Serbest Meslek.
        /// </summary>
        internal static string eFreeJob {
            get {
                return ResourceManager.GetString("eFreeJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E- Fatura.
        /// </summary>
        internal static string eInvoice {
            get {
                return ResourceManager.GetString("eInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Müstahsil.
        /// </summary>
        internal static string eManufacturer {
            get {
                return ResourceManager.GetString("eManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mutabakat.
        /// </summary>
        internal static string eReconciliation {
            get {
                return ResourceManager.GetString("eReconciliation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hatalılar.
        /// </summary>
        internal static string faulty {
            get {
                return ResourceManager.GetString("faulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İzibiz Masaüstü | Anasayfa.
        /// </summary>
        internal static string formHomePage {
            get {
                return ResourceManager.GetString("formHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İzibiz Masaüstü | E-Fatura İşlemleri.
        /// </summary>
        internal static string formInvoice {
            get {
                return ResourceManager.GetString("formInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İzibiz Masaüstü | Giriş.
        /// </summary>
        internal static string formLoginPage {
            get {
                return ResourceManager.GetString("formLoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İzibiz Masaüstü | E-Fatura Durum Görüntüle.
        /// </summary>
        internal static string frmShowInvoiceStatus {
            get {
                return ResourceManager.GetString("frmShowInvoiceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura Al.
        /// </summary>
        internal static string getInvoice {
            get {
                return ResourceManager.GetString("getInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelen Faturalar.
        /// </summary>
        internal static string incomingInvoice {
            get {
                return ResourceManager.GetString("incomingInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taslak Faturalar Listesi.
        /// </summary>
        internal static string listDraftInvoice {
            get {
                return ResourceManager.GetString("listDraftInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Fatura Listele.
        /// </summary>
        internal static string listInvoice {
            get {
                return ResourceManager.GetString("listInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yap.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı veya şifre boş bırakılamaz.
        /// </summary>
        internal static string loginBadRequest {
            get {
                return ResourceManager.GetString("loginBadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giris yapılamadı.. Kullanıcı adı ve kontrol ediniz...
        /// </summary>
        internal static string loginWarring {
            get {
                return ResourceManager.GetString("loginWarring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +Yeni Fatura.
        /// </summary>
        internal static string newInvoice {
            get {
                return ResourceManager.GetString("newInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pdf İndir.
        /// </summary>
        internal static string pdfDownload {
            get {
                return ResourceManager.GetString("pdfDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Önizleme.
        /// </summary>
        internal static string preview {
            get {
                return ResourceManager.GetString("preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yenile.
        /// </summary>
        internal static string refresh {
            get {
                return ResourceManager.GetString("refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Et.
        /// </summary>
        internal static string reject {
            get {
                return ResourceManager.GetString("reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönderilen Faturalar.
        /// </summary>
        internal static string sentInvoice {
            get {
                return ResourceManager.GetString("sentInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayarlar.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreyi Göster.
        /// </summary>
        internal static string showPassword {
            get {
                return ResourceManager.GetString("showPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarılı Durum Değiştirme.
        /// </summary>
        internal static string succesChangeState {
            get {
                return ResourceManager.GetString("succesChangeState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum Değiştirme Başarısız.
        /// </summary>
        internal static string unsuccesChangeState {
            get {
                return ResourceManager.GetString("unsuccesChangeState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum Güncelle.
        /// </summary>
        internal static string updateState {
            get {
                return ResourceManager.GetString("updateState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı.
        /// </summary>
        internal static string usurname {
            get {
                return ResourceManager.GetString("usurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uyarı.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faturaya yanıt süresi kanuni olarak 8 gündür. Faturanın yanıt süresi geçtiği için yanıt verilemez.
        /// </summary>
        internal static string warning8Day {
            get {
                return ResourceManager.GetString("warning8Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEMEL FATURAYA YANIT VERILMEZ.
        /// </summary>
        internal static string warningBasicInvoice {
            get {
                return ResourceManager.GetString("warningBasicInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faturaya yanıt verildiği için ikinci yanıt verilemez.
        /// </summary>
        internal static string warningHasAnswer {
            get {
                return ResourceManager.GetString("warningHasAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen bir açıklama yazınız.
        /// </summary>
        internal static string writeDescription {
            get {
                return ResourceManager.GetString("writeDescription", resourceCulture);
            }
        }
    }
}
