//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace izibiz.COMMON.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("izibiz.COMMON.Language.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kabul Et.
        /// </summary>
        public static string accept {
            get {
                return ResourceManager.GetString("accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesap Tipi.
        /// </summary>
        public static string accountType {
            get {
                return ResourceManager.GetString("accountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekle.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama Ekle.
        /// </summary>
        public static string addDescription {
            get {
                return ResourceManager.GetString("addDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekleme Başarılı.
        /// </summary>
        public static string addedSucc {
            get {
                return ResourceManager.GetString("addedSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satır Ekle.
        /// </summary>
        public static string addRow {
            get {
                return ResourceManager.GetString("addRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seri Ön Ek Ekle.
        /// </summary>
        public static string addSeriName {
            get {
                return ResourceManager.GetString("addSeriName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tekrar Gönder.
        /// </summary>
        public static string againSent {
            get {
                return ResourceManager.GetString("againSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arşiv Fatura Sayısı.
        /// </summary>
        public static string archiveInvCount {
            get {
                return ResourceManager.GetString("archiveInvCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arşiv Raporları.
        /// </summary>
        public static string archiveReport {
            get {
                return ResourceManager.GetString("archiveReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arşiv Gönderim Şekli.
        /// </summary>
        public static string archiveSendingType {
            get {
                return ResourceManager.GetString("archiveSendingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ba Döküman tutarı.
        /// </summary>
        public static string baDocAmount {
            get {
                return ResourceManager.GetString("baDocAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ba Döküman Adeti.
        /// </summary>
        public static string baDocPiece {
            get {
                return ResourceManager.GetString("baDocPiece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bs Döküman Tutarı.
        /// </summary>
        public static string bsDocAmount {
            get {
                return ResourceManager.GetString("bsDocAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bs Döküman Adeti.
        /// </summary>
        public static string bsDocPiece {
            get {
                return ResourceManager.GetString("bsDocPiece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesaplanan Tutar.
        /// </summary>
        public static string calculatedTax {
            get {
                return ResourceManager.GetString("calculatedTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İptal Et.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Databaseye ye kayıt basarısız.
        /// </summary>
        public static string cannotSaveDb {
            get {
                return ResourceManager.GetString("cannotSaveDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content dıskten sılınmıs ve servısten getırılemedı.
        /// </summary>
        public static string cantGetContent {
            get {
                return ResourceManager.GetString("cantGetContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taşıyıcı.
        /// </summary>
        public static string carrier {
            get {
                return ResourceManager.GetString("carrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taşıyıcı Unvan.
        /// </summary>
        public static string carrierTitle {
            get {
                return ResourceManager.GetString("carrierTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taşıyıcı Vkn/Tckn.
        /// </summary>
        public static string carrierVknTckn {
            get {
                return ResourceManager.GetString("carrierVknTckn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oluşturma Tarihi.
        /// </summary>
        public static string cDate {
            get {
                return ResourceManager.GetString("cDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bölüm.
        /// </summary>
        public static string chapter {
            get {
                return ResourceManager.GetString("chapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bölüm Bitiş.
        /// </summary>
        public static string chapterEnd {
            get {
                return ResourceManager.GetString("chapterEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bölüm Başlangıç.
        /// </summary>
        public static string chapterStart {
            get {
                return ResourceManager.GetString("chapterStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil Seçimi.
        /// </summary>
        public static string chooseLanguage {
            get {
                return ResourceManager.GetString("chooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temizle.
        /// </summary>
        public static string clear {
            get {
                return ResourceManager.GetString("clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem yapmak istediğiniz faturanın bulunduğu satırın uzerıne tıklayınız..
        /// </summary>
        public static string clickRowInvoice {
            get {
                return ResourceManager.GetString("clickRowInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cari Mutabakat Tarihi.
        /// </summary>
        public static string cmDate {
            get {
                return ResourceManager.GetString("cmDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cari Mutabakatlar.
        /// </summary>
        public static string cmReconcilations {
            get {
                return ResourceManager.GetString("cmReconcilations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oluştur.
        /// </summary>
        public static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oluşturma Tarihi.
        /// </summary>
        public static string createDate {
            get {
                return ResourceManager.GetString("createDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para Birimi.
        /// </summary>
        public static string currencyCode {
            get {
                return ResourceManager.GetString("currencyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mevcut Tutar.
        /// </summary>
        public static string currentAmount {
            get {
                return ResourceManager.GetString("currentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih.
        /// </summary>
        public static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database tarafında bır sorun cıktı !.
        /// </summary>
        public static string dbFault {
            get {
                return ResourceManager.GetString("dbFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlçe.
        /// </summary>
        public static string district {
            get {
                return ResourceManager.GetString("district", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boş bırakmayınız lütfen.
        /// </summary>
        public static string dontEmpty {
            get {
                return ResourceManager.GetString("dontEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelen faturalar &apos;D:\\temp\\GELEN\\&apos; klasorune kaydedılmıstır.
        /// </summary>
        public static string downInvSaveFolder {
            get {
                return ResourceManager.GetString("downInvSaveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taslak Arşivler.
        /// </summary>
        public static string draftArchives {
            get {
                return ResourceManager.GetString("draftArchives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taslak Faturalar.
        /// </summary>
        public static string draftInvoice {
            get {
                return ResourceManager.GetString("draftInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E- Arşiv.
        /// </summary>
        public static string eArchive {
            get {
                return ResourceManager.GetString("eArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E Arşiv Taslak Faturaları.
        /// </summary>
        public static string eArchiveDraftInvoices {
            get {
                return ResourceManager.GetString("eArchiveDraftInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E Arşiv Taslak Faturaları Listele.
        /// </summary>
        public static string eArchiveDraftInvoicesList {
            get {
                return ResourceManager.GetString("eArchiveDraftInvoicesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E Arşiv Faturaları.
        /// </summary>
        public static string eArchiveInvoices {
            get {
                return ResourceManager.GetString("eArchiveInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E Arşiv Fatura Raporları Listele.
        /// </summary>
        public static string eArchiveReportList {
            get {
                return ResourceManager.GetString("eArchiveReportList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E Arşiv Tip.
        /// </summary>
        public static string eArchiveType {
            get {
                return ResourceManager.GetString("eArchiveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-İrsailye.
        /// </summary>
        public static string eDispatch {
            get {
                return ResourceManager.GetString("eDispatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E- Serbest Meslek.
        /// </summary>
        public static string eFreeJob {
            get {
                return ResourceManager.GetString("eFreeJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E- Fatura.
        /// </summary>
        public static string eInvoice {
            get {
                return ResourceManager.GetString("eInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Müstahsil.
        /// </summary>
        public static string eManufacturer {
            get {
                return ResourceManager.GetString("eManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BA BS Mutabakatlar.
        /// </summary>
        public static string emReconcilations {
            get {
                return ResourceManager.GetString("emReconcilations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarf Id.
        /// </summary>
        public static string envelopeIdentifier {
            get {
                return ResourceManager.GetString("envelopeIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mutabakat.
        /// </summary>
        public static string eReconciliation {
            get {
                return ResourceManager.GetString("eReconciliation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hatalılar.
        /// </summary>
        public static string faulty {
            get {
                return ResourceManager.GetString("faulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İzibiz Masaüstü | E-Arşiv İşlemleri.
        /// </summary>
        public static string formArchive {
            get {
                return ResourceManager.GetString("formArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İzibiz Masaüstü | E-Fatura Oluştur.
        /// </summary>
        public static string FormCreateInvoice {
            get {
                return ResourceManager.GetString("FormCreateInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İzibiz Masaüstü | Seri Ön Ek Seçimi.
        /// </summary>
        public static string formDialogSeriName {
            get {
                return ResourceManager.GetString("formDialogSeriName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İzibiz Masaüstü | Anasayfa.
        /// </summary>
        public static string formHomePage {
            get {
                return ResourceManager.GetString("formHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İzibiz Masaüstü | E-Fatura İşlemleri.
        /// </summary>
        public static string formInvoice {
            get {
                return ResourceManager.GetString("formInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İzibiz Masaüstü | Giriş.
        /// </summary>
        public static string formLoginPage {
            get {
                return ResourceManager.GetString("formLoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İzibiz Desktop | Reconcilation.
        /// </summary>
        public static string formReconcilation {
            get {
                return ResourceManager.GetString("formReconcilation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İzibiz Masaüstü | Html Önizleme.
        /// </summary>
        public static string formView {
            get {
                return ResourceManager.GetString("formView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İzibiz Masaüstü | E-Fatura Durum Görüntüle.
        /// </summary>
        public static string frmShowInvoiceStatus {
            get {
                return ResourceManager.GetString("frmShowInvoiceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönderen Mail.
        /// </summary>
        public static string fromAlias {
            get {
                return ResourceManager.GetString("fromAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portaldan.
        /// </summary>
        public static string fromPortal {
            get {
                return ResourceManager.GetString("fromPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gib Kullanıcı Listesi Al.
        /// </summary>
        public static string getGibUserList {
            get {
                return ResourceManager.GetString("getGibUserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reddedilenler.
        /// </summary>
        public static string getRejected {
            get {
                return ResourceManager.GetString("getRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raporlananlar.
        /// </summary>
        public static string getReported {
            get {
                return ResourceManager.GetString("getReported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İmzalı Xml Al.
        /// </summary>
        public static string getSignedXml {
            get {
                return ResourceManager.GetString("getSignedXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gib Onaylanma Tarihi.
        /// </summary>
        public static string gibConfirmationDate {
            get {
                return ResourceManager.GetString("gibConfirmationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gib Durum Açıklama.
        /// </summary>
        public static string gibSatusDescription {
            get {
                return ResourceManager.GetString("gibSatusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gib Gönderme Tarihi.
        /// </summary>
        public static string gibSendDate {
            get {
                return ResourceManager.GetString("gibSendDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gib Durum Kod.
        /// </summary>
        public static string gibStatusCode {
            get {
                return ResourceManager.GetString("gibStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gib Kullanıcı Listesi.
        /// </summary>
        public static string gibUserList {
            get {
                return ResourceManager.GetString("gibUserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secili arsiv raporları basarıyla Kaydedıldı.
        /// </summary>
        public static string hasIdArchiveReportSave {
            get {
                return ResourceManager.GetString("hasIdArchiveReportSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nolu faturalara basarıyla maıl gonderıldı.
        /// </summary>
        public static string hasIdInvoiceSendMail {
            get {
                return ResourceManager.GetString("hasIdInvoiceSendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nolu mutabak daha once gonderılmıs tekrar gonderemezsınız.
        /// </summary>
        public static string hasIdReconBeforeSending {
            get {
                return ResourceManager.GetString("hasIdReconBeforeSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nolu faturalar daha onceden ıptal edılmıs  bunlar ısleme alınmayacak devam etmek istiyor musunuz.
        /// </summary>
        public static string hasNoInvoiceBeforeCanceled {
            get {
                return ResourceManager.GetString("hasNoInvoiceBeforeCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anasayfa.
        /// </summary>
        public static string homePage {
            get {
                return ResourceManager.GetString("homePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelen Faturalar.
        /// </summary>
        public static string incomingInvoice {
            get {
                return ResourceManager.GetString("incomingInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İnternet Satış Bilgisi.
        /// </summary>
        public static string internetSalesInformation {
            get {
                return ResourceManager.GetString("internetSalesInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura Başlık.
        /// </summary>
        public static string invoiceChapter {
            get {
                return ResourceManager.GetString("invoiceChapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura Bilgileri.
        /// </summary>
        public static string invoiceInformation {
            get {
                return ResourceManager.GetString("invoiceInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura Türü.
        /// </summary>
        public static string invType {
            get {
                return ResourceManager.GetString("invType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönderildi Mi.
        /// </summary>
        public static string isSend {
            get {
                return ResourceManager.GetString("isSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Düzenlenme Tarihi.
        /// </summary>
        public static string issueDate {
            get {
                return ResourceManager.GetString("issueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taslak Faturalar Listesi.
        /// </summary>
        public static string listDraftInvoice {
            get {
                return ResourceManager.GetString("listDraftInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrele.
        /// </summary>
        public static string listFilter {
            get {
                return ResourceManager.GetString("listFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Fatura Listele.
        /// </summary>
        public static string listInvoice {
            get {
                return ResourceManager.GetString("listInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portala Yükle.
        /// </summary>
        public static string loadPortal {
            get {
                return ResourceManager.GetString("loadPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yap.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı veya şifre boş bırakılamaz.
        /// </summary>
        public static string loginBadRequest {
            get {
                return ResourceManager.GetString("loginBadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giris yapılamadı.. Kullanıcı adı ve kontrol ediniz...
        /// </summary>
        public static string loginWarring {
            get {
                return ResourceManager.GetString("loginWarring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E posta.
        /// </summary>
        public static string mail {
            get {
                return ResourceManager.GetString("mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Durumu.
        /// </summary>
        public static string mailStatus {
            get {
                return ResourceManager.GetString("mailStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Durum kodu.
        /// </summary>
        public static string mailStatusCode {
            get {
                return ResourceManager.GetString("mailStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aracı.
        /// </summary>
        public static string middleman {
            get {
                return ResourceManager.GetString("middleman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para Birimi.
        /// </summary>
        public static string moneyType {
            get {
                return ResourceManager.GetString("moneyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İsim.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +Yeni Fatura.
        /// </summary>
        public static string newInvoice {
            get {
                return ResourceManager.GetString("newInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Mutabakat.
        /// </summary>
        public static string newReconcilation {
            get {
                return ResourceManager.GetString("newReconcilation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hayır.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura Getirilemedi.
        /// </summary>
        public static string noGetInvoice {
            get {
                return ResourceManager.GetString("noGetInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nolu faturalar uygun degil bu yuzden guncellenmedı.
        /// </summary>
        public static string noInvNotUpdated {
            get {
                return ResourceManager.GetString("noInvNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nolu faturalar guncellendı.
        /// </summary>
        public static string noInvUpdated {
            get {
                return ResourceManager.GetString("noInvUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gosterilecek mutabakat bulanamadı.
        /// </summary>
        public static string noReconcilation {
            get {
                return ResourceManager.GetString("noReconcilation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gösterilecek faturanız yok.
        /// </summary>
        public static string noShowInvoice {
            get {
                return ResourceManager.GetString("noShowInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gösterilecek hatalı faturanız yok.
        /// </summary>
        public static string notFaultyInv {
            get {
                return ResourceManager.GetString("notFaultyInv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamam.
        /// </summary>
        public static string okey {
            get {
                return ResourceManager.GetString("okey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem Başarısız.
        /// </summary>
        public static string operationFailed {
            get {
                return ResourceManager.GetString("operationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödenecek Tutar.
        /// </summary>
        public static string paidAmount {
            get {
                return ResourceManager.GetString("paidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödeme Bilgisi.
        /// </summary>
        public static string paymentInformation {
            get {
                return ResourceManager.GetString("paymentInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pdf İndir.
        /// </summary>
        public static string pdfDownload {
            get {
                return ResourceManager.GetString("pdfDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dönem.
        /// </summary>
        public static string period {
            get {
                return ResourceManager.GetString("period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dönem Bitiş.
        /// </summary>
        public static string periodEnd {
            get {
                return ResourceManager.GetString("periodEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dönem Başlangıç.
        /// </summary>
        public static string periodStart {
            get {
                return ResourceManager.GetString("periodStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Önizleme.
        /// </summary>
        public static string preview {
            get {
                return ResourceManager.GetString("preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Adı.
        /// </summary>
        public static string productName {
            get {
                return ResourceManager.GetString("productName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil Kimlik.
        /// </summary>
        public static string profileid {
            get {
                return ResourceManager.GetString("profileid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İl.
        /// </summary>
        public static string province {
            get {
                return ResourceManager.GetString("province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miktar.
        /// </summary>
        public static string quantity {
            get {
                return ResourceManager.GetString("quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerçek.
        /// </summary>
        public static string real {
            get {
                return ResourceManager.GetString("real", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alıcı.
        /// </summary>
        public static string receiver {
            get {
                return ResourceManager.GetString("receiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alıcı VKN/TCKN.
        /// </summary>
        public static string receiverVkn {
            get {
                return ResourceManager.GetString("receiverVkn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yenile.
        /// </summary>
        public static string refresh {
            get {
                return ResourceManager.GetString("refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reddet.
        /// </summary>
        public static string reject {
            get {
                return ResourceManager.GetString("reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satır Sil.
        /// </summary>
        public static string removeRow {
            get {
                return ResourceManager.GetString("removeRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapor No.
        /// </summary>
        public static string reportNo {
            get {
                return ResourceManager.GetString("reportNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raporlanma  Durumu.
        /// </summary>
        public static string reportState {
            get {
                return ResourceManager.GetString("reportState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to islem yapabılmek ıcın tablodan bir veriye  tıklayınız.
        /// </summary>
        public static string rowClickForProses {
            get {
                return ResourceManager.GetString("rowClickForProses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satır Bilgileri.
        /// </summary>
        public static string rowInformation {
            get {
                return ResourceManager.GetString("rowInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senaryo.
        /// </summary>
        public static string scenario {
            get {
                return ResourceManager.GetString("scenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen bir alıcı posta kutusu seçiniz..
        /// </summary>
        public static string selectAlias {
            get {
                return ResourceManager.GetString("selectAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sadece aynı kisiye olanları secebılırsınız.
        /// </summary>
        public static string selectOnePerson {
            get {
                return ResourceManager.GetString("selectOnePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen fatura id için bir seri ön eki seçiniz..
        /// </summary>
        public static string selectSeriName {
            get {
                return ResourceManager.GetString("selectSeriName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönder.
        /// </summary>
        public static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönderen Ad.
        /// </summary>
        public static string senderName {
            get {
                return ResourceManager.GetString("senderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönderen VKN/TCKN.
        /// </summary>
        public static string senderVkn {
            get {
                return ResourceManager.GetString("senderVkn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönderim Tipi.
        /// </summary>
        public static string sendingType {
            get {
                return ResourceManager.GetString("sendingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nolu faturalara yanıt gonderıldı.
        /// </summary>
        public static string sendResponseToInvoice {
            get {
                return ResourceManager.GetString("sendResponseToInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maile Gönder.
        /// </summary>
        public static string sendToMail {
            get {
                return ResourceManager.GetString("sendToMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönderilen Faturalar.
        /// </summary>
        public static string sentInvoice {
            get {
                return ResourceManager.GetString("sentInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seri name; bos olamaz,karakter sayısı 3 den kucuk veya kucuk harf olamaz.
        /// </summary>
        public static string seriNameControl {
            get {
                return ResourceManager.GetString("seriNameControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hizmet Toplam Tutar.
        /// </summary>
        public static string ServiceTotalAmount {
            get {
                return ResourceManager.GetString("ServiceTotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayarlar.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreyi Göster.
        /// </summary>
        public static string showPassword {
            get {
                return ResourceManager.GetString("showPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imzali Xml.
        /// </summary>
        public static string signedXml {
            get {
                return ResourceManager.GetString("signedXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum.
        /// </summary>
        public static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum Kodu.
        /// </summary>
        public static string statusCode {
            get {
                return ResourceManager.GetString("statusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum Açıklama.
        /// </summary>
        public static string statusDesc {
            get {
                return ResourceManager.GetString("statusDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secılı faturalar basarıyla iptal edildi.
        /// </summary>
        public static string succCancelSelectedInvoice {
            get {
                return ResourceManager.GetString("succCancelSelectedInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarılı Durum Değiştirme.
        /// </summary>
        public static string succesChangeState {
            get {
                return ResourceManager.GetString("succesChangeState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarılı.
        /// </summary>
        public static string succesful {
            get {
                return ResourceManager.GetString("succesful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yükleme işlemi başarılı..
        /// </summary>
        public static string successLoad {
            get {
                return ResourceManager.GetString("successLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servisten durum sorgulama işlemi basarılı.
        /// </summary>
        public static string succGetStatus {
            get {
                return ResourceManager.GetString("succGetStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Db ye  durum kaydetme basarılı.
        /// </summary>
        public static string succSaveStatus {
            get {
                return ResourceManager.GetString("succSaveStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mail gönderme işlemi basarılı.
        /// </summary>
        public static string succSendMail {
            get {
                return ResourceManager.GetString("succSendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tedarikçi.
        /// </summary>
        public static string supplier {
            get {
                return ResourceManager.GetString("supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyad.
        /// </summary>
        public static string surname {
            get {
                return ResourceManager.GetString("surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura Al.
        /// </summary>
        public static string takeInvoice {
            get {
                return ResourceManager.GetString("takeInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İmzalı Xml Al.
        /// </summary>
        public static string takeSignedXml {
            get {
                return ResourceManager.GetString("takeSignedXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kdv Tutarı.
        /// </summary>
        public static string taxAmount {
            get {
                return ResourceManager.GetString("taxAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kdv Oranı.
        /// </summary>
        public static string taxPercent {
            get {
                return ResourceManager.GetString("taxPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlık.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alıcı Mail.
        /// </summary>
        public static string toAlias {
            get {
                return ResourceManager.GetString("toAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam.
        /// </summary>
        public static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam Tutar.
        /// </summary>
        public static string totalAmount {
            get {
                return ResourceManager.GetString("totalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vergiler Dahil Toplam Tutar.
        /// </summary>
        public static string totalAmountWithTax {
            get {
                return ResourceManager.GetString("totalAmountWithTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüzel.
        /// </summary>
        public static string tuzel {
            get {
                return ResourceManager.GetString("tuzel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip.
        /// </summary>
        public static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birim.
        /// </summary>
        public static string unit {
            get {
                return ResourceManager.GetString("unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birim Miktarı.
        /// </summary>
        public static string unitPrice {
            get {
                return ResourceManager.GetString("unitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum Değiştirme Başarısız.
        /// </summary>
        public static string unsuccesChangeState {
            get {
                return ResourceManager.GetString("unsuccesChangeState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Db ye  durum kaydetme basarısız.
        /// </summary>
        public static string unSuccSaveStatus {
            get {
                return ResourceManager.GetString("unSuccSaveStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum Güncelle.
        /// </summary>
        public static string updateState {
            get {
                return ResourceManager.GetString("updateState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı.
        /// </summary>
        public static string usurname {
            get {
                return ResourceManager.GetString("usurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ettn.
        /// </summary>
        public static string uuid {
            get {
                return ResourceManager.GetString("uuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eklemek istediğiniz deger zaten eklenmiş.
        /// </summary>
        public static string valueAlreadyAdded {
            get {
                return ResourceManager.GetString("valueAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vkn/Tckn.
        /// </summary>
        public static string vknTckn {
            get {
                return ResourceManager.GetString("vknTckn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yanıt Bekleyenler.
        /// </summary>
        public static string waitResponse {
            get {
                return ResourceManager.GetString("waitResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönderici posta kutusu bilgilerini cekmek istiyor musunuz?.
        /// </summary>
        public static string wantGetUserList {
            get {
                return ResourceManager.GetString("wantGetUserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uyarı.
        /// </summary>
        public static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faturaya yanıt süresi kanuni olarak 8 gündür. Faturanın yanıt süresi geçtiği için yanıt verilemez.
        /// </summary>
        public static string warning8Day {
            get {
                return ResourceManager.GetString("warning8Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEMEL FATURAYA YANIT VERILMEZ.
        /// </summary>
        public static string warningBasicInvoice {
            get {
                return ResourceManager.GetString("warningBasicInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faturaya yanıt verildiği için ikinci yanıt verilemez.
        /// </summary>
        public static string warningHasAnswer {
            get {
                return ResourceManager.GetString("warningHasAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to temel fatura veya 8 gün gecmiş faturaların durum sorgulaması yapılamaz.
        /// </summary>
        public static string warningStateShow {
            get {
                return ResourceManager.GetString("warningStateShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoşgeldiniz.
        /// </summary>
        public static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Unzip.
        /// </summary>
        public static string withUnzip {
            get {
                return ResourceManager.GetString("withUnzip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Zip.
        /// </summary>
        public static string withZip {
            get {
                return ResourceManager.GetString("withZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen bir açıklama yazınız.
        /// </summary>
        public static string writeDescription {
            get {
                return ResourceManager.GetString("writeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evet.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
